channels:
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - numpy=1.17.4
  - pandas=0.25.3
  - networkx=2.4
  - matplotlib=3.1.2
  - pydot=1.4.1
  - requests=2.22.0
  - sparqlwrapper=1.8.5
  - rdflib=5.0.0
  - pip:
    - netwulf==0.1.4
